1. Import the numpy package under the name np (★☆☆)


In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)


In [2]:
print(np.__version__)

print("\nNumPy configuration:")
np.show_config()

1.26.2

NumPy configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2306486572304
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.2
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.5
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_6

3. Create a null vector of size 10 (★☆☆)


In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array (★☆☆)


In [4]:
arr = np.zeros((10, 10))

memory_size = arr.nbytes
print(memory_size)

800


5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [5]:
print(np.info(np.add))


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [6]:
null_vector = np.zeros(10)

null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 (★☆☆)


In [7]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last) (★☆☆)


In [8]:
vector = np.array([1, 2, 3, 4, 5])

reversed_vector = vector[::-1]

print(reversed_vector)

[5 4 3 2 1]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)


In [9]:
vector = np.arange(9)

matrix = vector.reshape(3, 3)
 
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
arr = np.array([1, 2, 0, 0, 4, 0])

indices = np.nonzero(arr)

print(indices)

(array([0, 1, 4], dtype=int64),)


11. Create a 3x3 identity matrix (★☆☆)


In [11]:
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values (★☆☆)


In [12]:
random_array = np.random.rand(3, 3, 3)

print(random_array)

[[[0.72333982 0.42383496 0.40690085]
  [0.54563372 0.49068529 0.78680697]
  [0.64839469 0.04572613 0.78297379]]

 [[0.35197508 0.1743152  0.19234763]
  [0.55408834 0.45287286 0.10703327]
  [0.46060082 0.18327062 0.55536537]]

 [[0.43505203 0.01257468 0.15498259]
  [0.57951969 0.23115471 0.73625497]
  [0.48974397 0.00573109 0.77754469]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


In [13]:
random_array = np.random.rand(10, 10)

# Find the minimum and maximum values
min_value = random_array.min()
max_value = random_array.max()

print(random_array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

[[0.89918375 0.1527907  0.40090417 0.31666199 0.37906429 0.50321757
  0.42680505 0.67942614 0.4384055  0.98276416]
 [0.32573586 0.31372956 0.11381905 0.10138724 0.85259867 0.29475203
  0.21837732 0.73995118 0.88535093 0.57921554]
 [0.23070258 0.96103014 0.00267136 0.484271   0.07532282 0.54922096
  0.89629566 0.06306288 0.4524462  0.42342573]
 [0.40407504 0.39423527 0.61172505 0.81321283 0.21471247 0.19128144
  0.09928783 0.83723374 0.24825043 0.80597466]
 [0.16537661 0.22845266 0.00983638 0.71843798 0.04907938 0.87724479
  0.41497826 0.41236658 0.78050172 0.59679196]
 [0.24150011 0.4488728  0.6199394  0.55497484 0.42502696 0.64363337
  0.53871866 0.03921025 0.30774517 0.91115244]
 [0.85652329 0.31263229 0.18988344 0.81523111 0.81589192 0.33628952
  0.82700127 0.81839562 0.86239426 0.12361885]
 [0.21699231 0.20855743 0.06229993 0.27627973 0.50600722 0.65337417
  0.27371346 0.51842236 0.67199015 0.55634015]
 [0.70259484 0.37839873 0.86434953 0.957343   0.92769213 0.35353087
  0.09437239

14. Create a random vector of size 30 and find the mean value (★☆☆)


In [14]:

# Create a random vector of size 30
random_vector = np.random.rand(30)

# Find the mean value
mean_value = random_vector.mean()

print("Mean value:", mean_value)

Mean value: 0.43440324822302473


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


In [15]:
# Define the dimensions of the 2D array
rows = 5
cols = 5

# Create a 2D array filled with zeros
array = np.zeros((rows, cols))

# Set the border elements to 1
array[0, :] = 1  # Top row
array[-1, :] = 1  # Bottom row
array[:, 0] = 1  # Left column
array[:, -1] = 1  # Right column

print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? (★☆☆)


In [16]:
# Example existing array
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Get the dimensions of the existing array
rows, cols = existing_array.shape

# Create a new array with increased dimensions (adding 2 to both rows and columns)
new_array = np.zeros((rows + 2, cols + 2))

# Place the existing array within the new array, leaving a border of 0s
new_array[1:-1, 1:-1] = existing_array

print(new_array)

[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0.]
 [0. 4. 5. 6. 0.]
 [0. 7. 8. 9. 0.]
 [0. 0. 0. 0. 0.]]


17. What is the result of the following expression? (★☆☆)

In [17]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


In [18]:

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Assign values 1, 2, 3, 4 just below the diagonal
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


In [19]:
# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Set alternate rows and columns to 1
matrix[1::2, ::2] = 1  # odd rows, even columns
matrix[::2, 1::2] = 1  # even rows, odd columns

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


In [20]:
# Define the shape of the array
shape = (6, 7, 8)

# Calculate the flat index of the 100th element
flat_index_100th = 99  # 100th element, adjusted for zero-based indexing

# Calculate the z-index
z_index = flat_index_100th % shape[2]

# Calculate the remaining index after removing z-index
remaining_index = flat_index_100th // shape[2]

# Calculate the y-index
y_index = remaining_index % shape[1]

# Calculate the x-index
x_index = remaining_index // shape[1]

print("Index (x, y, z) of the 100th element:", (x_index, y_index, z_index))

Index (x, y, z) of the 100th element: (1, 5, 3)


21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)


In [21]:

# Create a 2x2 checkerboard pattern
checkerboard = np.array([[0, 1], [1, 0]])

# Use tile function to create an 8x8 checkerboard matrix
checkerboard_8x8 = np.tile(checkerboard, (4, 4))

print(checkerboard_8x8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. Normalize a 5x5 random matrix (★☆☆)


In [22]:
# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Calculate the mean and standard deviation of the matrix
mean = np.mean(random_matrix)
std_dev = np.std(random_matrix)

# Normalize the matrix
normalized_matrix = (random_matrix - mean) / std_dev

print("Original matrix:")
print(random_matrix)
print("\nNormalized matrix:")
print(normalized_matrix)

Original matrix:
[[0.40190649 0.3704038  0.59623339 0.93461541 0.70981748]
 [0.8381317  0.10843284 0.86903934 0.6758212  0.07618485]
 [0.57806865 0.65968861 0.59752609 0.63870017 0.8591621 ]
 [0.23916491 0.05589731 0.32028381 0.54704402 0.98737175]
 [0.27235121 0.88703116 0.89689708 0.76442957 0.65855303]]

Normalized matrix:
[[-0.65274757 -0.76711283  0.05272387  1.28116346  0.46507199]
 [ 0.93089543 -1.71815479  1.04310045  0.34165418 -1.83522576]
 [-0.01322019  0.28308749  0.05741682  0.20689247  1.00724279]
 [-1.24355378 -1.90887629 -0.94906512 -0.12584995  1.47268657]
 [-1.12307643  1.10841677  1.14423333  0.6633321   0.27896497]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


In [23]:
# Define the custom dtype for RGBA color
color_dtype = np.dtype([('R', np.uint8),  # Red channel
                        ('G', np.uint8),  # Green channel
                        ('B', np.uint8),  # Blue channel
                        ('A', np.uint8)]) # Alpha channel

# Example usage of the custom dtype
color = np.array((255, 0, 0, 255), dtype=color_dtype)  # Red color with full opacity

print("RGBA Color:", color)

RGBA Color: (255, 0, 0, 255)


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


In [24]:
# Create a 5x3 matrix
matrix1 = np.random.rand(5, 3)

# Create a 3x2 matrix
matrix2 = np.random.rand(3, 2)

# Multiply the matrices to get the real matrix product
result = np.dot(matrix1, matrix2)
# Alternatively, you can also use the @ operator
# result = matrix1 @ matrix2

print("Matrix 1 (5x3):")
print(matrix1)
print("\nMatrix 2 (3x2):")
print(matrix2)
print("\nResult (5x2) of the matrix multiplication:")
print(result)

Matrix 1 (5x3):
[[0.91552208 0.38028911 0.68894032]
 [0.57150901 0.02380073 0.24757394]
 [0.51697666 0.27376457 0.38342485]
 [0.17449211 0.32268231 0.34927828]
 [0.80588132 0.73615595 0.08759114]]

Matrix 2 (3x2):
[[0.95272085 0.08234968]
 [0.419168   0.97773317]
 [0.14991842 0.87812727]]

Result (5x2) of the matrix multiplication:
[[1.13492684 1.05219151]
 [0.59158094 0.28773577]
 [0.66477024 0.64693738]
 [0.35386362 0.63657735]
 [1.08948448 0.86304433]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Negate elements between 3 and 8 (inclusive)
array[(array >= 3) & (array <= 8)] *= -1

print("Negated array:")
print(array)

Negated array:
[ 1  2 -3 -4 -5 -6 -7 -8  9 10]
